#!/usr/bin/env python3
"""DoctorMandDesign — Presentation Generator (Jinja2 + WeasyPrint)

Usage:
    python3 generate.py --data example-data.json --output output/slides.pdf
    python3 generate.py --data example-data.json --output output/slides.pdf --prompt "Generate a pitch for..."
    python3 generate.py --input old-template.html --output output/legacy.pdf
"""
import argparse
import json
import sys
import tempfile
from pathlib import Path

from weasyprint import HTML
from jinja2 import Environment, FileSystemLoader, select_autoescape

SCRIPT_DIR = Path(__file__).parent
DEFAULT_OUTPUT = SCRIPT_DIR / "output" / "slides.pdf"

LOCALES_DIR = SCRIPT_DIR / "locales"
DEFAULT_LOCALE = "ru"


def load_locale(lang: str) -> dict:
    """Load locale strings from locales/<lang>.json."""
    locale_file = LOCALES_DIR / f"{lang}.json"
    if not locale_file.exists():
        if lang != DEFAULT_LOCALE:
            print(f"WARNING: Locale '{lang}' not found, falling back to '{DEFAULT_LOCALE}'", file=sys.stderr)
        locale_file = LOCALES_DIR / f"{DEFAULT_LOCALE}.json"
    with open(locale_file, "r", encoding="utf-8") as f:
        return json.load(f)


def generate(data_path: str = None, input_path: str = None, output_path: str = None,
             prompt: str = None):
    output = Path(output_path) if output_path else DEFAULT_OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)

    # ── Mode 1: JSON → Jinja2 ──
    if data_path:
        data_f = Path(data_path)
        if not data_f.exists():
            print(f"ERROR: Data file not found: {data_f}")
            sys.exit(1)
        with open(data_f, "r", encoding="utf-8") as f:
            payload = json.load(f)

        # Determine language
        lang = payload.get("lang", "ru")
        if lang not in ("ru", "en"):
            print(f"WARNING: Unknown lang '{lang}', using 'ru'", file=sys.stderr)
            lang = "ru"

        # Load locale
        locale = load_locale(lang)
        payload["_locale"] = locale
        payload["_lang"] = lang

        env = Environment(
            loader=FileSystemLoader(searchpath=[
                str(SCRIPT_DIR),
                str(SCRIPT_DIR / "templates"),
                str(SCRIPT_DIR / "templates" / "slides"),
            ]),
            autoescape=select_autoescape(["html", "xml"]),
        )
        tmpl = env.get_template("template.j2")
        rendered_html = tmpl.render(**payload)

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".html", encoding="utf-8", delete=False, dir=str(SCRIPT_DIR)
        ) as tmp_f:
            tmp_f.write(rendered_html)
            tmp_path = tmp_f.name

        print(f"Data     : {data_f}")
        print(f"Lang     : {lang}")
        print(f"Output   : {output}")

        HTML(filename=tmp_path).write_pdf(target=str(output))

        try:
            Path(tmp_path).unlink()
        except OSError:
            pass

    # ── Mode 2: Legacy HTML direct ──
    elif input_path:
        template = Path(input_path)
        if not template.exists():
            print(f"ERROR: Template not found: {template}")
            sys.exit(1)

        print(f"Template : {template}")
        print(f"Output   : {output}")

        HTML(filename=str(template)).write_pdf(target=str(output))

    else:
        print("ERROR: Provide either --data (JSON) or --input (HTML)")
        sys.exit(1)

    size_kb = output.stat().st_size / 1024
    print(f"Done! {size_kb:.1f} KB")


def generate_from_prompt(prompt: str, output_path: Path):
    """Generate a simple presentation from a text prompt."""
    # Create a minimal JSON structure
    data = {
        "lang": "en",
        "title": "AI Generated Presentation",
        "subtitle": "Generated from prompt: " + (prompt[:50] + "..." if len(prompt) > 50 else prompt),
        "slides": [
            {
                "type": "hero",
                "title": prompt[:100],
                "subtitle": "Generated by AI",
                "footer": "",
            }
        ]
    }
    # Write to temp file
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, dir=str(SCRIPT_DIR)) as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        temp_path = f.name
    
    try:
        generate(data_path=temp_path, output_path=str(output_path))
    finally:
        try:
            Path(temp_path).unlink()
        except OSError:
            pass


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate presentation PDF")
    parser.add_argument("--data", "-d", help="Path to JSON data file (uses Jinja2→template.j2)")
    parser.add_argument("--input", "-i", help="Raw HTML template (legacy mode)")
    parser.add_argument("--output", "-o", help="PDF output path")
    parser.add_argument("--prompt", "-p", help="AI prompt for content generation (requires --data)")
    args = parser.parse_args()
    
    # Determine output path
    output_path = Path(args.output) if args.output else DEFAULT_OUTPUT
    
    # Handle AI generation mode
    if args.prompt:
        if not args.data:
            print("ERROR: --prompt requires --data to provide base template", file=sys.stderr)
            sys.exit(1)
        # For now, we just generate a simple presentation from prompt
        # In future, this could call an LLM to enrich the JSON data
        generate_from_prompt(args.prompt, output_path)
        exit(0)
    
    generate(data_path=args.data, input_path=args.input, output_path=str(output_path))
